<?php

require_once(__DIR__.'/../../03/libsPHP/themeSettings/'.$themeURL.'.php');

 $groups=array(

   'group_MainIndex' => array(    
                        'aus',
                        'aut',
                        'bel',
                        'can',
                        'che',
                        'deu',
                        'dnk',
                        'esp',
                        'fin',
                        'fra',
                        'gbr',
                        'grc',
                        'irl',
                        'ita',
                        'jpn',
                        'kor',
                        'lux',
                        'nld',
                        'nor',
                        'nzl',
                        'prt',
                        'swe',
                        'usa',
                        'chl',
                        'cze',
                        'est',
                        'hun',
                        'isl',
                        'isr',
                        'mex',
                        'pol',
                        'svk',
                        'svn',
                        'tur',
                        'arg',
                        'bra',
                        'chn',
                        'idn',
                        'ind',
                        'rus',
                        'zaf',
                        'oecd',
                    ),


    'group_OECD' => array(                          
                        'aus',
                        'aut',
                        'bel',
                        'can',
                        'che',
                        'chl',
                        'cze',
                        'deu',
                        'dnk',
                        'esp',
                        'est',
                        'fin',
                        'fra',
                        'gbr',
                        'grc',
                        'hun',
                        'irl',
                        'isl',
                        'isr',
                        'ita',
                        'jpn',
                        'kor',
                        'lux',
                        'mex',
                        'nld',
                        'nor',
                        'nzl',
                        'oecd',
                        'pol',
                        'prt',
                        'svk',
                        'svn',
                        'swe',
                        'tur',
                        'usa'
                    ),


    'group_G20' => array(    
                        'aus',
                        'can',
                        'deu',
                        'esp',
                        'fra',
                        'gbr',
                        'ita',
                        'jpn',
                        'kor',
                        'usa',
                        'mex',
                        'tur',
                        'arg',
                        'bra',
                        'chn',
                        'idn',
                        'ind',
                        'rus',
                        'sau',
                        'zaf'
                    ),


    'group_EU28' => array(    
                        'aut',
                        'bel',
                        'bgr',
                        'cyp',
                        'deu',
                        'dnk',
                        'esp',
                        'fin',
                        'fra',
                        'gbr',
                        'grc',
                        'hrv',
                        'irl',
                        'ita',
                        'lux',
                        'lva',
                        'ltu',
                        'mlt',
                        'nld',
                        'prt',
                        'swe',
                        'cze',
                        'est',
                        'hun',
                        'pol',
                        'svk',
                        'svn',
                        'rou',
                        'eu',
                    ),


    'group_EMU' => array(    
                        'aut',
                        'bel',
//                        'bgr',
                        'cyp',
                        'deu',
//                        'dnk',
                        'esp',
                        'fin',
                        'fra',
//                        'gbr',
                        'grc',
//                        'hrv',
                        'irl',
                        'ita',
                        'lux',
                        'lva',
                        'ltu',
                        'mlt',
                        'nld',
                        'prt',
//                        'swe',
//                        'cze',
                        'est',
//                        'hun',
//                        'pol',
                        'svk',
                        'svn',
//                        'rou',
                        'eur',
                    ),
        
);


$groups['group_standardMap'] = array_diff($groups['group_EMU'], array('eur'));

$ISO2_ISO3=array(
    'AE' => 'ARE', 'AF' => 'AFG', 'AL' => 'ALB', 'AM' => 'ARM', 'AO' => 'AGO',
    'AR' => 'ARG', 'AT' => 'AUT', 'AU' => 'AUS', 'AZ' => 'AZE', 'BA' => 'BIH',
    'BD' => 'BGD', 'BE' => 'BEL', 'BF' => 'BFA', 'BG' => 'BGR', 'BI' => 'BDI',
    'BJ' => 'BEN', 'BN' => 'BRN', 'BO' => 'BOL', 'BR' => 'BRA', 'BS' => 'BHS',
    'BT' => 'BTN', 'BW' => 'BWA', 'BY' => 'BLR', 'BZ' => 'BLZ', 'CA' => 'CAN',
    'CD' => 'COD', 'CF' => 'CAF', 'CG' => 'COG', 'CH' => 'CHE', 'CI' => 'CIV',
    'CL' => 'CHL', 'CM' => 'CMR', 'CN' => 'CHN', 'CO' => 'COL', 'CR' => 'CRI',
    'CU' => 'CUB', 'CY' => 'CYP', 'CZ' => 'CZE', 'DE' => 'DEU', 'DJ' => 'DJI',
    'DK' => 'DNK', 'DO' => 'DOM', 'DZ' => 'DZA', 'EC' => 'ECU', 'EE' => 'EST',
    'EG' => 'EGY', 'ER' => 'ERI', 'ES' => 'ESP', 'ET' => 'ETH', 'FI' => 'FIN',
    'FJ' => 'FJI', 'FK' => 'FLK', 'FR' => 'FRA', 'GA' => 'GAB', 'GB' => 'GBR',
    'GE' => 'GEO', 'GH' => 'GHA', 'GL' => 'GRL', 'GM' => 'GMB', 'GN' => 'GIN',
    'GQ' => 'GNQ', 'GR' => 'GRC', 'GT' => 'GTM', 'GW' => 'GNB', 'GY' => 'GUY',
    'HN' => 'HND', 'HR' => 'HRV', 'HT' => 'HTI', 'HU' => 'HUN', 'ID' => 'IDN',
    'IE' => 'IRL', 'IL' => 'ISR', 'IN' => 'IND', 'IQ' => 'IRQ', 'IR' => 'IRN',
    'IS' => 'ISL', 'IT' => 'ITA', 'JM' => 'JAM', 'JO' => 'JOR', 'JP' => 'JPN',
    'KE' => 'KEN', 'KG' => 'KGZ', 'KH' => 'KHM', 'KP' => 'PRK', 'KR' => 'KOR',
    'KW' => 'KWT', 'KZ' => 'KAZ', 'LA' => 'LAO', 'LB' => 'LBN', 'LK' => 'LKA',
    'LR' => 'LBR', 'LS' => 'LSO', 'LT' => 'LTU', 'LU' => 'LUX', 'LV' => 'LVA',
    'LY' => 'LBY', 'MA' => 'MAR', 'MD' => 'MDA', 'ME' => 'MNE', 'MG' => 'MDG',
    'MK' => 'MKD', 'ML' => 'MLI', 'MT' => 'MLT', 'MM' => 'MMR', 'MN' => 'MNG',
    'MR' => 'MRT', 'MW' => 'MWI', 'MX' => 'MEX', 'MY' => 'MYS', 'MZ' => 'MOZ',
    'NA' => 'NAM', 'NC' => 'NCL', 'NE' => 'NER', 'NG' => 'NGA', 'NI' => 'NIC',
    'NL' => 'NLD', 'NO' => 'NOR', 'NP' => 'NPL', 'NZ' => 'NZL', 'OM' => 'OMN',
    'PA' => 'PAN', 'PE' => 'PER', 'PG' => 'PNG', 'PH' => 'PHL', 'PK' => 'PAK',
    'PL' => 'POL', 'PS' => 'PSE', 'PT' => 'PRT', 'PY' => 'PRY', 'QA' => 'QAT',
    'RO' => 'ROU', 'RS' => 'SRB', 'RU' => 'RUS', 'RW' => 'RWA', 'SA' => 'SAU',
    'SB' => 'SLB', 'SD' => 'SDN', 'SE' => 'SWE', 'SI' => 'SVN', 'SK' => 'SVK',
    'SL' => 'SLE', 'SN' => 'SEN', 'SO' => 'SOM', 'SR' => 'SUR', 'SS' => 'SDS',
    'SV' => 'SLV', 'SY' => 'SYR', 'SZ' => 'SWZ', 'TD' => 'TCD', 'TF' => 'ATF',
    'TG' => 'TGO', 'TH' => 'THA', 'TJ' => 'TJK', 'TL' => 'TLS', 'TM' => 'TKM',
    'TN' => 'TUN', 'TR' => 'TUR', 'TT' => 'TTO', 'TZ' => 'TZA', 'UA' => 'UKR',
    'UG' => 'UGA', 'US' => 'USA', 'UY' => 'URY', 'UZ' => 'UZB', 'VE' => 'VEN',
    'VN' => 'VNM', 'VU' => 'VUT', 'YE' => 'YEM', 'ZA' => 'ZAF', 'ZM' => 'ZMB',
    'ZW' => 'ZWE', 'EA' => 'EUR',
);

//add all share languages on embed.php drop-down
// languages for the landing page
$shareLanguagesProjects['']=array_keys($shareLanguages);


$Colors = array (

    'RedBlue10' => array(
        '#67001F',
        '#B2182B',
        '#D6604D',
        '#F4A582',
        '#FDDBC7',
        '#D1E5F0',
        '#92C5DE',
        '#4393C3',
        '#2166AC',
        '#053061',
       ),

    'Blue9' => array(
        '#F7FBFF',
        '#DEEBF7',
        '#C6DBEF',
        '#9ECAE1',
        '#6BAED6',
        '#4292C6',
        '#2171B5',
        '#08519C',
        '#08306B',
       ),

    'Brown9' => array(
        '#FFF5EB',
        '#FEE6CE',
        '#FDD0A2',
        '#FDAE6B',
        '#FD8D3C',
        '#F16913',
        '#D94801',
        '#A63603',
        '#7F2704',
       ),

    'Purple9' => array(
        '#FCFBFD',
        '#EFEDF5',
        '#DADAEB',
        '#BCBDDC',
        '#9E9AC8',
        '#807DBA',
        '#6A51A3',
        '#54278F',
        '#3F007D',
       ),

    'Red9' => array(
        '#FFF5F0',
        '#FEE0D2',
        '#FCBBA1',
        '#FC9272',
        '#FB6A4A',
        '#EF3B2C',
        '#CB181D',
        '#A50F15',
        '#67000D',
       ),

    'Green9' => array(
       "#f7fcfd","#e5f5f9","#ccece6","#99d8c9","#66c2a4","#41ae76","#238b45","#006d2c","#00441b"
    ),

    
);


?>
