<?php
if (isset($lang['group'])) {
$counterpartAreas = array_map(function ($v) {
  return array_map('trim', preg_split('@<br ?/?>@', $v));
}, $lang['group']);
unset($lang['group']);
return;
}
$counterpartAreas = [
  '4a' => [
    'Committee of Regions',
    'Council of the European Union ',
    'Court of Auditors',
    'Court of Justice',
    'Economic and Social Committee',
    'EU-Africa Infrastructure Trust Fund',
    'European Atomic Energy Community',
    'European Banking Authority',
    'European Coal and Steel Community',
    'European Commission',
    'European Council',
    'European Development Fund',
    'European Insurance and Occupational Pensions Authority',
    'European Investment Bank',
    'European Investment Fund',
    'European Monetary System',
    'European Parliament',
    'European Securities and Markets Authority',
    'Facility for Euro-Mediterranean Investment and Partnership',
    'Neighbourhood Investment Facility',
    'Other small European Union Institutions and agencies',
  ],
  '9a' => [
    'African Development Bank',
    'African Development Fund',
    'African Export-Import Bank',
    'Andean Development Corporation',
    'Arab Monetary Fund',
    'Asian Development Bank',
    'Asian Development Fund',
    'Asian Infrastructure Investment Bank ',
    'Banco Latino Americano De Comercio Exterior',
    'Bank for International Settlements',
    'Banque arabe pour le développement économique en Afrique',
    'Banque Centrale des Etats de l`Afrique de l`Ouest',
    'Banque des Etats de l`Afrique Centrale',
    'Black Sea Trade and Development Banks',
    'Caribbean Development Bank',
    'Central African States Development Bank',
    'Central American Bank for Economic Integration',
    'Council of Europe',
    'Council of Europe Development Bank',
    'Eastern Caribbean Central Bank',
    'Eurasian Development Bank',
    'European Bank for Reconstruction and Development',
    'European Broadcasting Union/Union européenne de radio-télévision',
    'European Centre for Medium-Range Weather Forecasts',
    'European Company for the Financing of Railroad Rolling Stock',
    'European Molecular Biology Laboratory',
    'European Organisation for Nuclear Research',
    'European Organisation for the Exploitation of Meteorological Satellites',
    'European Organisation for the Safety of Air Navigation',
    'European Patent Office',
    'European Southern Observatory',
    'European Space Agency',
    'European Telecommunications Satellite Organisation',
    'Fondo Latino Americano de Reservas',
    'Fonds Belgo-Congolais d\'Amortissement et de Gestion',
    'Fonds spécial unifié de développement',
    'Food and Agriculture Organisation',
    'Inter-American Development Bank',
    'Inter-American Investment Corporation',
    'International Atomic Energy Agency',
    'International Bank for Economic Co-operation',
    'International Bank for Reconstruction and Development',
    'International Centre for Settlement of Investment Disputes',
    'International Committee of the Red Cross',
    'International Development Association',
    'International Finance Corporation',
    'International finance Facility for Immunisation',
    'International Fund for Agricultural Development',
    'International Investment Bank',
    'International Labour Organisation',
    'International Monetary Fund',
    'International Organisation for Migration',
    'International Telecommunication Union',
    'International Telecommunications Satellite Organisation',
    'International Union of Credit and Investment Insurers',
    'Islamic Development Bank',
    'Multilateral Investment Guarantee Agency',
    'Multilateral Lending Agencies',
    'Nordic Investment Bank',
    'North Atlantic Treaty Organisation',
    'Organisation for Economic Co-operation and Development',
    'Other International Financial Organisations',
    'Other International Non-Financial Organisations',
    'Other International Organisations (non-financial institutions)',
    'Paris Club Creditor Institutions',
    'Rest of UN Organisations',
    'United Nations Children Fund',
    'United Nations Educational, Scientific and Cultural Organisation',
    'United Nations High Commissioner for Refugees',
    'United Nations Relief and Works Agency for Palestine',
    'West African Economic and Monetary Union',
    'World Health Organisation',
    'World Trade Organisation',
  ],
  'r12' => [
    'Andorra',
    'Anguilla',
    'Antigua and Barbuda',
    'Aruba',
    'Bahamas',
    'Bahrain',
    'Barbados',
    'Belize',
    'Bermuda',
    'Cayman Islands',
    'Cook Island',
    'Curacao',
    'Dominica',
    'Gibraltar',
    'Grenada',
    'Guernsey',
    'Hong Kong, China',
    'Isle of Man',
    'Jersey',
    'Lebanon',
    'Liberia',
    'Liechtenstein',
    'Marshall Islands',
    'Mauritius',
    'Montserrat',
    'Nauru',
    'Niue',
    'Panama',
    'Philippines',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'Seychelles',
    'Singapore',
    'Sint Maarten (Dutch part)',
    'Turks and Caicos Islands',
    'Vanuatu',
    'Virgin Islands, British',
    'Virgin Islands, U.S.',
  ],
];
