<?php

$shareLanguages=array(
        'bg' => 'Български',
        'cs' => 'Čeština',
        'da' => 'Dansk',
        'de' => 'Deutsch',
        'et' => 'Eesti keel',
        'en' => 'English',
        'es' => 'Español',
        'el' => 'Eλληνικά',
        'fr' => 'Français',
        'hr' => 'Hrvatski',
        'it' => 'Italiano',
        'lv' => 'Latviešu',
        'lt' => 'Lietuvių',
        'hu' => 'Magyar',
        'mt' => 'Malti',
        'nl' => 'Nederlands',
        'pl' => 'Polski',
        'pt' => 'Português',
        'ro' => 'Română',
        'sk' => 'Slovenčina',
        'sl' => 'Slovenščina',
        'fi' => 'Suomi',
        'sv' => 'Svenska',
);

$bankLinks = array (
   'European Central Bank' => 'http://www.euro.ecb.europa.eu/',
   'Banque nationale de Belgique / Nationale Bank van België' => 'http://www.nbb.be/',
   'Deutsche Bundesbank' => 'http://www.bundesbank.de/',
   'Eesti Pank' => 'http://www.eestipank.ee/',
   'Central Bank of Ireland' => 'http://www.centralbank.ie/',
   'Τράπεζα της Ελλάδος' => 'http://www.bankofgreece.gr/',
   'Banco de España' => 'http://www.bde.es/',
   'Banque de France' => 'http://www.banque-france.fr/',
   'Banca d’Italia' => 'http://www.bancaditalia.it/',
   'Κεντρική Τράπεζα της Κύπρου' => 'http://www.centralbank.gov.cy/',
   'Latvijas Banka' => 'http://www.bank.lv/',
   'Lietuvos bankas' => 'http://www.lb.lt/',
   'Banque centrale du Luxembourg' => 'http://www.bcl.lu/',
   'Central Bank of Malta / Bank Ċentrali ta’ Malta' => 'http://www.centralbankmalta.org/',
   'De Nederlandsche Bank' => 'http://www.dnb.nl/',
   'Oesterreichische Nationalbank' => 'http://www.oenb.at/',
   'Banco de Portugal' => 'http://www.bportugal.pt/',
   'Banka Slovenije' => 'http://www.bsi.si/',
   'Národná banka Slovenska' => 'http://www.nbs.sk/',
   'Suomen Pankki / Finlands Bank' => 'http://www.suomenpankki.fi',
);
