<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Depósitos',
  'bank-interest-rates-loans' => 'Empréstimos',
  'banks-balance-sheet-deposits' => 'Depósitos',
  'banks-balance-sheet-loans' => 'Empréstimos',
  'competitiveness-indicators' => 'Por preço e custo',
  'corporates-debt-ratio-in-the-euro-area' => 'O rácio da dívida das empresas varia entre os países da área do euro',
  'crypto-assets' => 'Criptoativos: evolução e perspetivas',
  'current-account-balance-of-the-euro-area' => 'Saldo da balança corrente da área do euro',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Evolução do valor de mercado das ações cotadas diverge nos vários países da área do euro',
  'current-account-by-main-counterparties' => 'Balança corrente por principais contrapartes',
  'digpub-1' => '<p>Ver a publicação digital</p>
<p>Moeda, crédito e taxas de juro do banco central</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Taxas de juro da área do euro aplicáveis a empréstimos bancários',
  'external-debt' => 'Dívida externa',
  'external-sector' => 'Balança corrente',
  'financial-account' => 'Balança financeira',
  'financing-and-investment-dynamics' => 'Num país/na área do euro',
  'financing-and-investment-dynamics2' => 'Comparar',
  'financing-and-investment-dynamics_main' => 'Dinâmica do financiamento e do investimento',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'As taxas de crescimento do crédito à habitação registam uma subida constante na área do euro',
  'inflation-rates' => 'Índice de preços no consumidor',
  'international-investment-position' => 'Posição de investimento internacional',
  'investment-funds-assets' => 'Ativos',
  'investment-funds-in-the-euro-area' => 'Fundos de investimento da área do euro',
  'investment-funds-liabilities' => 'Passivos',
  'investment-funds-policies' => 'Por política de investimento',
  'investment-funds-types' => 'Por tipo de fundo',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Emissão de títulos de dívida por residentes na área do euro',
  'macro-economic-indicators' => 'Indicadores macroeconómicos',
  'macroeconomic-scoreboard' => 'Painel de avaliação macroeconómico',
  'payment-statistics' => 'Pagamentos com cartão na área do euro duplicam numa década',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'A tendência positiva dos empréstimos bancários a empresas na área do euro prossegue',
  'reserve-assets' => 'Ativos de reserva',
  'securities-debt-securities' => 'Títulos de dívida',
  'securities-quoted-shares' => 'Ações cotadas',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'A taxa de juro de curto prazo do euro (€STR) é a taxa de juro <em>overnight</em> do mercado monetário do euro',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'A €STR tem-se situado num intervalo entre ‑0,583 e ‑0,511, desde que foi lançada em 2 de outubro de 2019.',
));
