<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Indėliai',
  'bank-interest-rates-loans' => 'Paskolos',
  'banks-balance-sheet-deposits' => 'Indėliai',
  'banks-balance-sheet-loans' => 'Paskolos',
  'competitiveness-indicators' => 'Pagal kainą ir sąnaudas',
  'corporates-debt-ratio-in-the-euro-area' => 'Euro zonos šalių bendrovių skolos santykis',
  'crypto-assets' => 'Kriptoturtas: pokyčiai ir perspektyvos',
  'current-account-balance-of-the-euro-area' => 'Euro zonos einamosios sąskaitos balansas',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Biržinių akcijų rinkos vertė įvairiose euro zonos šalyse kinta nevienodai',
  'current-account-by-main-counterparties' => 'Einamoji sąskaita pagal pagrindines sandorio šalis',
  'digpub-1' => '<p>Eiti į skaitmeninį leidinį</p>
<p>Pinigai, kreditai ir oficialios palūkanų normos</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Euro zonos bankų paskolų palūkanų normos',
  'external-debt' => 'Skola užsieniui',
  'external-sector' => 'Einamoji sąskaita',
  'financial-account' => 'Finansinė sąskaita',
  'financing-and-investment-dynamics' => 'Viena šalis / zona',
  'financing-and-investment-dynamics2' => 'Palyginti dvi šalis / zonas',
  'financing-and-investment-dynamics_main' => 'Finansavimo ir investavimo dinamika',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Euro zonoje būsto paskolų augimo tempas stabiliai didėja',
  'inflation-rates' => 'Vartotojų kainų indeksas',
  'international-investment-position' => 'Tarptautinių investicijų balansas',
  'investment-funds-assets' => 'Turtas',
  'investment-funds-in-the-euro-area' => 'Euro zonos investiciniai fondai',
  'investment-funds-liabilities' => 'Įsipareigojimai',
  'investment-funds-policies' => 'Pagal investavimo politiką',
  'investment-funds-types' => 'Pagal fondo tipą',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Euro zonos rezidentų skolos vertybinių popierių emisija',
  'macro-economic-indicators' => 'Makroekonominiai rodikliai',
  'macroeconomic-scoreboard' => 'Makroekonominių rodiklių suvestinė',
  'payment-statistics' => 'Mokėjimų kortele euro zonoje skaičius per dešimtmetį padvigubėjo',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Tęsiasi teigiama bankų skolinimo įmonėms tendencija euro zonoje',
  'reserve-assets' => 'Atsargos',
  'securities-debt-securities' => 'Skolos vertybiniai popieriai',
  'securities-quoted-shares' => 'Biržinės akcijos',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Euro trumpalaikio skolinimosi norma (€STR) – euro vienos nakties pinigų rinkos palūkanų norma',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Nuo 2019 m. spalio 2 d., kai €STR buvo paskelbta pirmą kartą, ji svyravo nuo –0,583 iki –0,511. 2021 m. kovo 29 d. €STR buvo –0,570.',
));
