<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Hoiused',
  'bank-interest-rates-loans' => 'Laenud',
  'banks-balance-sheet-deposits' => 'Hoiused',
  'banks-balance-sheet-loans' => 'Laenud',
  'competitiveness-indicators' => 'Hindade ja kulude kaupa',
  'corporates-debt-ratio-in-the-euro-area' => 'Ettevõtete võlakoormus on euroala riikide lõikes erinev.',
  'crypto-assets' => 'Krüptovarad: arengusuunad ja väljavaated',
  'current-account-balance-of-the-euro-area' => 'Euroala jooksevkonto saldo',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Noteeritud aktsiate turuväärtuse areng on euroala riikide lõikes erinev',
  'current-account-by-main-counterparties' => 'Jooksevkonto (peamiste vastaspoolte järgi)',
  'digpub-1' => '<p>Digiväljaanne</p>
<p>Raha, krediit ja keskpanga intressimäärad</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Pangalaenude intressimäärad euroalal',
  'external-debt' => 'Välisvõlg',
  'external-sector' => 'Jooksevkonto',
  'financial-account' => 'Finantskonto',
  'financing-and-investment-dynamics' => 'Üks piirkond',
  'financing-and-investment-dynamics2' => 'Võrdle kaht piirkonda',
  'financing-and-investment-dynamics_main' => 'Rahastamise ja investeeringute dünaamika',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Eluasemelaenude maht euroala riikides suureneb pidevalt.',
  'inflation-rates' => 'Tarbijahinnaindeks',
  'international-investment-position' => 'Rahvusvaheline investeerimispositsioon',
  'investment-funds-assets' => 'Varad',
  'investment-funds-in-the-euro-area' => 'Investeerimisfondid euroalal',
  'investment-funds-liabilities' => 'Kohustused',
  'investment-funds-policies' => 'Investeerimispoliitika alusel',
  'investment-funds-types' => 'Fondiliigi alusel',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Euroala residentide võlaväärtpaberite emiteerimine',
  'macro-economic-indicators' => 'Makromajanduslikud näitajad',
  'macroeconomic-scoreboard' => 'Makromajandustulemused',
  'payment-statistics' => 'Euroala kaardimaksed on kümne aastaga kahekordistunud',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Euroala ettevõtetele antud laenude kasv jätkub',
  'reserve-assets' => 'Reservvara',
  'securities-debt-securities' => 'Võlaväärtpaberid',
  'securities-quoted-shares' => 'Noteeritud aktsiad',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Euro lühiajaline intressimäär (€STR) on euro üleöörahaturu intressimäär',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Alates selle kasutuselevõtust 2. oktoobril 2019 on €STR kõikunud vahemikus –0,583 kuni –0,511. 29. märtsil 2021 oli euro lühiajaline intressimäär –0,570.',
));
