<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Vklady',
  'bank-interest-rates-loans' => 'Úvery',
  'banks-balance-sheet-deposits' => 'Vklady',
  'banks-balance-sheet-loans' => 'Úvery',
  'competitiveness-indicators' => 'Podľa cien a nákladov',
  'corporates-debt-ratio-in-the-euro-area' => 'Rozdiely v pomere zadlženosti podnikov v eurozóne',
  'crypto-assets' => 'Kryptoaktíva: vývoj a perspektívy',
  'current-account-balance-of-the-euro-area' => 'Saldo bežného účtu eurozóny',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Odlišný vývoj trhovej hodnoty kótovaných akcií v jednotlivých krajinách eurozóny',
  'current-account-by-main-counterparties' => 'Bežný účet podľa hlavných protistrán',
  'digpub-1' => '<p>Prejsť na digitálnu publikáciu</p>
<p>Peniaze, úvery a úrokové sadzby centrálnej banky</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Úrokové sadzby bankových úverov v eurozóne',
  'external-debt' => 'Zahraničný dlh',
  'external-sector' => 'Bežný účet',
  'financial-account' => 'Finančný účet',
  'financing-and-investment-dynamics' => 'Za jednu oblasť',
  'financing-and-investment-dynamics2' => 'Porovnať dve oblasti',
  'financing-and-investment-dynamics_main' => 'Dynamika financovania a investícií',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Miery rastu úverov na kúpu nehnuteľností na bývanie v eurozóne stabilne rastú',
  'inflation-rates' => 'Index spotrebiteľských cien',
  'international-investment-position' => 'Medzinárodná investičná pozícia',
  'investment-funds-assets' => 'Aktíva',
  'investment-funds-in-the-euro-area' => 'Investičné fondy v eurozóne',
  'investment-funds-liabilities' => 'Pasíva',
  'investment-funds-policies' => 'Podľa investičného zamerania',
  'investment-funds-types' => 'Podľa druhu fondu',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Emisia dlhových cenných papierov rezidentov eurozóny',
  'macro-economic-indicators' => 'Makroekonomické ukazovatele',
  'macroeconomic-scoreboard' => 'Hodnotiaca tabuľka',
  'payment-statistics' => 'Kartové platby v eurozóne sa za posledné desaťročie zdvojnásobili',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Pozitívny trend bankových úverov podnikom v eurozóne pokračuje',
  'reserve-assets' => 'Rezervné aktíva',
  'securities-debt-securities' => 'Dlhové cenné papiere',
  'securities-quoted-shares' => 'Kótované akcie',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Krátkodobá eurová sadzba €STR je eurová jednodňová úroková sadzba peňažného trhu',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Sadzba €STR sa od svojho zavedenia 2. októbra 2019 pohybovala v rozmedzí -0,583 až -0,511.',
));
