<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Депозити',
  'bank-interest-rates-loans' => 'Кредити',
  'banks-balance-sheet-deposits' => 'Депозити',
  'banks-balance-sheet-loans' => 'Кредити',
  'competitiveness-indicators' => 'По цени и разходи',
  'corporates-debt-ratio-in-the-euro-area' => 'Съотношението на дълга на предприятията е различно в различните държави от еврозоната.',
  'crypto-assets' => 'Криптоактиви – развитие и перспективи',
  'current-account-balance-of-the-euro-area' => 'Салдо по текущата сметка на еврозоната',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Динамиката на пазарната стойност на котираните акции не е еднаква навсякъде в еврозоната',
  'current-account-by-main-counterparties' => 'Текуща сметка по основни контрагенти',
  'digpub-1' => '<p>Към цифровата публикация</p>
<p>Пари, кредит и централнобанкови лихвени проценти</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Лихвени проценти по банкови кредити в еврозоната',
  'external-debt' => 'Външен дълг',
  'external-sector' => 'Текуща сметка',
  'financial-account' => 'Финансова сметка',
  'financing-and-investment-dynamics' => 'За една зона',
  'financing-and-investment-dynamics2' => 'Сравнете две зони',
  'financing-and-investment-dynamics_main' => 'Динамика на финансирането и инвестициите',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Темпът на нарастване на жилищните кредити се повишава устойчиво в еврозоната',
  'inflation-rates' => 'Индекс на потребителските цени',
  'international-investment-position' => 'Международна инвестиционна позиция',
  'investment-funds-assets' => 'Активи',
  'investment-funds-in-the-euro-area' => 'Инвестиционни фондове в еврозоната',
  'investment-funds-liabilities' => 'Пасиви',
  'investment-funds-policies' => 'Според инвестиционната политика',
  'investment-funds-types' => 'Според вида фонд',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Емитиране на дългови ценни книжа от резиденти на еврозоната',
  'macro-economic-indicators' => 'Макроикономически показатели',
  'macroeconomic-scoreboard' => 'Табло с макроикономически показатели',
  'payment-statistics' => 'Картовите плащания в Европа са се удвоили за едно десетилетие',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Положителният тренд при банковото кредитиране за предприятия в еврозоната продължава',
  'reserve-assets' => 'Резервни активи',
  'securities-debt-securities' => 'Дългови ценни книжа',
  'securities-quoted-shares' => 'Котирани акции',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Краткосрочният лихвен процент в евро (€STR) е овърнайт лихвен процент в евро на паричния пазар',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => '€STR се движи в диапазона между -0,583 и -0,511 от въвеждането му на 2 октомври 2019 г. насам.',
));
