<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Dépôts',
  'bank-interest-rates-loans' => 'Prêts',
  'banks-balance-sheet-deposits' => 'Dépôts',
  'banks-balance-sheet-loans' => 'Prêts',
  'competitiveness-indicators' => 'En termes de prix et de coûts',
  'corporates-debt-ratio-in-the-euro-area' => 'Le taux d’endettement des entreprises varie dans la zone euro',
  'crypto-assets' => 'Crypto-actifs : évolutions et perspectives',
  'current-account-balance-of-the-euro-area' => 'Solde du compte des transactions courantes de la zone euro',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Les évolutions de la valeur de marché des actions cotées varient dans la zone euro',
  'current-account-by-main-counterparties' => 'Compte des transactions courantes par contreparties principales',
  'digpub-1' => '<p>Ouvrir la publication numérique</p>
<p>La monnaie, le crédit et les taux directeurs</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Taux d’intérêt des prêts bancaires dans la zone euro',
  'external-debt' => 'Dette extérieure',
  'external-sector' => 'Compte courant',
  'financial-account' => 'Compte financier',
  'financing-and-investment-dynamics' => 'Zone euro ou pays',
  'financing-and-investment-dynamics2' => 'Comparer (entre pays ou avec la zone euro)',
  'financing-and-investment-dynamics_main' => 'Dynamique de financement et d\'investissement',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Les taux de croissance des prêts au logement sont en constante augmentation dans la zone euro',
  'inflation-rates' => 'Indice des prix à la consommation',
  'international-investment-position' => 'Position extérieure',
  'investment-funds-assets' => 'Actifs',
  'investment-funds-in-the-euro-area' => 'Les OPC dans la zone euro',
  'investment-funds-liabilities' => 'Passifs',
  'investment-funds-policies' => 'Selon la politique d\'investissement',
  'investment-funds-types' => 'Selon le type de fonds',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Émission de titres de créance par les résidents de la zone euro',
  'macro-economic-indicators' => 'Indicateurs macroéconomiques',
  'macroeconomic-scoreboard' => 'Tableau de bord macroéconomique',
  'payment-statistics' => 'En l’espace de dix ans, les paiements par carte dans la zone euro ont doublé',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Poursuite de l’évolution positive des prêts bancaires aux entreprises dans la zone euro',
  'reserve-assets' => 'Avoirs de réserve',
  'securities-debt-securities' => 'Titres de créance',
  'securities-quoted-shares' => 'Actions cotées',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Le taux à court terme en euros (<em>euro short-term rate</em>, €STR) est le taux d’intérêt du marché monétaire au jour le jour en euros.',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'L’€STR a évolué dans une fourchette comprise entre -0,583 et -0,511 depuis son lancement le 2 octobre 2019.',
));
