<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Depositi',
  'bank-interest-rates-loans' => 'Prestiti',
  'banks-balance-sheet-deposits' => 'Depositi',
  'banks-balance-sheet-loans' => 'Prestiti',
  'competitiveness-indicators' => 'Prezzo e costo',
  'corporates-debt-ratio-in-the-euro-area' => 'Il rapporto debito delle società / PIL varia da un paese all’altro dell’area dell’euro',
  'crypto-assets' => 'Cripto-attività: sviluppi e prospettive',
  'current-account-balance-of-the-euro-area' => 'Saldo delle partite correnti dell’area dell’euro',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'L’andamento del valore di mercato delle azioni quotate varia all’interno dell’area dell’euro',
  'current-account-by-main-counterparties' => 'Conto corrente per principali controparti',
  'digpub-1' => '<p>Vai alla pubblicazione digitale</p>
<p>La moneta, il credito e i tassi di interesse della banca centrale</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Tassi di interesse dell’area dell’euro sui prestiti bancari',
  'external-debt' => 'Debito estero',
  'external-sector' => 'Conto corrente',
  'financial-account' => 'Conto finanziario',
  'financing-and-investment-dynamics' => 'Per un paese',
  'financing-and-investment-dynamics2' => 'Confronta due paesi',
  'financing-and-investment-dynamics_main' => 'Dinamiche dei finanziamenti e degli investimenti',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'I tassi di crescita dei mutui per l’acquisto di abitazioni aumentano costantemente nell’area dell’euro',
  'inflation-rates' => 'Indice dei prezzi al consumo',
  'international-investment-position' => 'Posizione patrimoniale sull’estero',
  'investment-funds-assets' => 'Attività',
  'investment-funds-in-the-euro-area' => 'Fondi comuni di investimento nell’area dell’euro',
  'investment-funds-liabilities' => 'Passività',
  'investment-funds-policies' => 'Per strategia di investimento',
  'investment-funds-types' => 'Per tipologia di fondo',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Emissione di titoli di debito da parte dei residenti nell’area dell’euro',
  'macro-economic-indicators' => 'Indicatori macroeconomici',
  'macroeconomic-scoreboard' => 'Quadro di valutazione macroeconomico',
  'payment-statistics' => 'I pagamenti con carta nell’area dell’euro sono raddoppiati in dieci anni',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Continua il trend positivo dei prestiti bancari alle società dell’area dell’euro',
  'reserve-assets' => 'Attività di riserva',
  'securities-debt-securities' => 'Titoli di debito',
  'securities-quoted-shares' => 'Azioni quotate',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Lo euro short-term rate (€STR) è il tasso di interesse overnight per i mercati monetari in euro',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Dopo la sua introduzione il 2 ottobre 2019 l’€STR ha oscillato all’interno di un intervallo compreso tra il -0,583 e il -0,511.',
));
