<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Καταθέσεις',
  'bank-interest-rates-loans' => 'Δάνεια',
  'banks-balance-sheet-deposits' => 'Καταθέσεις',
  'banks-balance-sheet-loans' => 'Δάνεια',
  'competitiveness-indicators' => 'Κατά τιμή και κόστος',
  'corporates-debt-ratio-in-the-euro-area' => 'Ο λόγος του χρέους των επιχειρήσεων διαφέρει μεταξύ των χωρών της ζώνης του ευρώ.',
  'crypto-assets' => 'Κρυπτογραφικά στοιχεία ενεργητικού: εξελίξεις και προοπτικές',
  'current-account-balance-of-the-euro-area' => 'Ισοζύγιο τρεχουσών συναλλαγών της ζώνης του ευρώ',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Οι εξελίξεις στην αγοραία αξία των εισηγμένων μετοχών ποικίλουν στη ζώνη του ευρώ',
  'current-account-by-main-counterparties' => 'Ισοζύγιο τρεχουσών συναλλαγών κατά βασικούς αντισυμβαλλομένους',
  'digpub-1' => '<p>Μετάβαση στην ψηφιακή έκδοση</p>
<p>Χρήμα, πιστώσεις και επιτόκια κεντρικής τράπεζας</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Επιτόκια των τραπεζικών δανείων στη ζώνη του ευρώ',
  'external-debt' => 'Εξωτερικό χρέος',
  'external-sector' => 'Ισοζύγιο τρεχουσών συναλλαγών',
  'financial-account' => 'Ισοζύγιο χρηματοοικονομικών συναλλαγών',
  'financing-and-investment-dynamics' => 'Ζώνη ευρώ/χώρα',
  'financing-and-investment-dynamics2' => 'Σύγκριση χωρών ή ζώνης ευρώ με χώρα',
  'financing-and-investment-dynamics_main' => 'Δυναμική χρηματοδότησης και επενδύσεων',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Οι ρυθμοί αύξησης των στεγαστικών δανείων επιταχύνονται σταθερά στη ζώνη του ευρώ',
  'inflation-rates' => 'Δείκτης Τιμών Καταναλωτή',
  'international-investment-position' => 'Διεθνής επενδυτική θέση',
  'investment-funds-assets' => 'Ενεργητικό',
  'investment-funds-in-the-euro-area' => 'Αμοιβαία κεφάλαια επενδυτικού χαρακτήρα στη ζώνη του ευρώ',
  'investment-funds-liabilities' => 'Παθητικό',
  'investment-funds-policies' => 'Κατά επενδυτική πολιτική',
  'investment-funds-types' => 'Κατά τύπο αμοιβαίου κεφαλαίου',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Έκδοση χρεογράφων από κατοίκους της ζώνης του ευρώ',
  'macro-economic-indicators' => 'Μακροοικονομικοί δείκτες',
  'macroeconomic-scoreboard' => 'Πίνακας μακροοικονομικών αποτελεσμάτων',
  'payment-statistics' => 'Οι πληρωμές με κάρτα στη ζώνη του ευρώ διπλασιάστηκαν σε μια δεκαετία',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Συνεχίζεται η θετική τάση των τραπεζικών δανείων προς τις επιχειρήσεις της ζώνης του ευρώ',
  'reserve-assets' => 'Συναλλαγματικά διαθέσιμα',
  'securities-debt-securities' => 'Χρεόγραφα',
  'securities-quoted-shares' => 'Εισηγμένες μετοχές',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Το βραχυπρόθεσμο επιτόκιο του ευρώ (€STR) είναι το επιτόκιο της χρηματαγοράς του ευρώ για τοποθετήσεις μίας ημέρας',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Το €STR κυμάνθηκε μεταξύ -0,583 και -0,511 μετά την πρώτη δημοσίευσή του στις 2 Οκτωβρίου 2019.',
));
