<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Deposito’s',
  'bank-interest-rates-loans' => 'Leningen',
  'banks-balance-sheet-deposits' => 'Deposito’s',
  'banks-balance-sheet-loans' => 'Financierings- en beleggingsdynamiek',
  'competitiveness-indicators' => 'Naar prijs en kosten',
  'corporates-debt-ratio-in-the-euro-area' => 'Schuldratio ondernemingen verschilt per land van het eurogebied',
  'crypto-assets' => 'Cryptoactiva: ontwikkelingen en perspectieven',
  'current-account-balance-of-the-euro-area' => 'Saldo op de lopende rekening van het eurogebied',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'De ontwikkelingen in de marktwaarde van beursgenoteerde aandelen lopen in het eurogebied uiteen',
  'current-account-by-main-counterparties' => 'Lopende rekening naar belangrijkste tegenpartijen',
  'digpub-1' => '<p>Ga naar de digitale publicatie</p>
<p>Geld, krediet en de rentetarieven van de centrale bank</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Rentetarieven in het eurogebied op bankleningen',
  'external-debt' => 'Externe schuld',
  'external-sector' => 'Lopende rekening',
  'financial-account' => 'Financiële rekening',
  'financing-and-investment-dynamics' => 'Voor één gebied',
  'financing-and-investment-dynamics2' => 'Twee gebieden vergelijken',
  'financing-and-investment-dynamics_main' => 'Financierings- en beleggingsdynamiek',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Groei van de woninghypotheken neemt gestaag toe in het eurogebied',
  'inflation-rates' => 'Consumptieprijsindex',
  'international-investment-position' => 'Internationale investeringspositie',
  'investment-funds-assets' => 'Activa',
  'investment-funds-in-the-euro-area' => 'Beleggingsfondsen in het eurogebied',
  'investment-funds-liabilities' => 'Passiva',
  'investment-funds-policies' => 'Naar beleggingsbeleid',
  'investment-funds-types' => 'Naar type fonds',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Uitgifte van schuldbewijzen door ingezetenen van het eurogebied',
  'macro-economic-indicators' => 'Macro-economische indicatoren',
  'macroeconomic-scoreboard' => 'Macro-economisch scorebord',
  'payment-statistics' => 'Eurogebied kent verdubbeling van kaartbetalingen in tien jaar',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'De positieve trend in leningen aan bedrijven in het eurogebied zet door',
  'reserve-assets' => 'Reserves',
  'securities-debt-securities' => 'Schuldbewijzen',
  'securities-quoted-shares' => 'Beursgenoteerde aandelen',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'De kortetermijnrente voor de euro (euro short-term rate – €STR) is de eendaagse geldmarktrente voor de euro',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Sinds de start op 2 oktober 2019 beweegt de €STR zich binnen de bandbreedte van -0,583 en -0,511.',
));
