<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'noguldījumi',
  'bank-interest-rates-loans' => 'kredīti',
  'banks-balance-sheet-deposits' => 'noguldījumi',
  'banks-balance-sheet-loans' => 'kredīti',
  'competitiveness-indicators' => 'cenu un izmaksu dalījumā',
  'corporates-debt-ratio-in-the-euro-area' => 'Nefinanšu sabiedrību parāda rādītājs dažādās euro zonas valstīs atšķiras',
  'crypto-assets' => 'Kriptoaktīvi – attīstība un perspektīva',
  'current-account-balance-of-the-euro-area' => 'Euro zonas tekošā konta bilance',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Kotēto akciju tirgus vērtību dinamika euro zonas valstīs atšķiras',
  'current-account-by-main-counterparties' => 'Tekošais konts galveno darījuma partneru dalījumā',
  'digpub-1' => '<p>Uz digitālo publikāciju</p>
<p>Nauda, kreditēšana un centrālo banku procentu likmes</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Euro zonas banku kredītu procentu likmes',
  'external-debt' => 'ārējais parāds',
  'external-sector' => 'tekošais konts',
  'financial-account' => 'finanšu konts',
  'financing-and-investment-dynamics' => 'viens reģions',
  'financing-and-investment-dynamics2' => 'divu reģionu salīdzinājums',
  'financing-and-investment-dynamics_main' => 'Finansēšanas un ieguldījumu dinamika',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Mājokļa iegādei izsniegto kredītu pieauguma temps euro zonā stabili pieaug',
  'inflation-rates' => 'patēriņa cenu indekss',
  'international-investment-position' => 'starptautisko investīciju bilance',
  'investment-funds-assets' => 'aktīvi',
  'investment-funds-in-the-euro-area' => 'Euro zonas ieguldījumu fondi',
  'investment-funds-liabilities' => 'pasīvi',
  'investment-funds-policies' => 'ieguldījumu politikas dalījumā',
  'investment-funds-types' => 'fondu veida dalījumā',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Euro zonas rezidentu emitētie parāda vērtspapīri',
  'macro-economic-indicators' => 'Makroekonomiskie rādītāji',
  'macroeconomic-scoreboard' => 'Makroekonomiskie rezultāti',
  'payment-statistics' => 'Karšu maksājumu skaits euro zonā pēdējo 10 gadu laikā pieaudzis vairāk nekā divas reizes',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Turpinās pozitīva nefinanšu sabiedrībām izsniegto euro zonas banku kredītu attīstības tendence',
  'reserve-assets' => 'rezerves aktīvi',
  'securities-debt-securities' => 'parāda vērtspapīri',
  'securities-quoted-shares' => 'biržas sarakstā iekļautās akcijas',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Euro īstermiņa procentu likme (€STR) ir euro naudas tirgus darījumu uz nakti procentu likme',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Kopš €STR ieviešanas 2019. gada 2. oktobrī tā svārstījusies robežās no –0.583 līdz –0.511. 2021. gada 29. martā tā bija –0.570.',
));
