<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Depożiti',
  'bank-interest-rates-loans' => 'Self',
  'banks-balance-sheet-deposits' => 'Depożiti',
  'banks-balance-sheet-loans' => 'Self',
  'competitiveness-indicators' => 'Skont il-prezz u l-kost',
  'corporates-debt-ratio-in-the-euro-area' => 'Il-proporzjon tad-dejn korporattiv ivarja madwar iż-żona tal-euro',
  'crypto-assets' => 'Kriptoassi: zviluppi u perspettivi',
  'current-account-balance-of-the-euro-area' => 'Bilanċ tal-kont kurrenti taż-żona tal-euro',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'L-iżviluppi fil-valur tas-suq ta’ ishma elenkati jistgħu jvarjaw fi ħdan iż-żona tal-euro',
  'current-account-by-main-counterparties' => 'Kont kurrenti skont kontropartijiet ewlenin',
  'digpub-1' => '<p>Mur fil-pubblikazzjoni diġitali</p>
<p>Flus, kreditu u rati tal-imgħax tal-bank ċentrali</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Rati tal-imgħax taż-żona tal-euro fuq self bankarju',
  'external-debt' => 'Dejn estern',
  'external-sector' => 'Kont kurrenti',
  'financial-account' => 'Kont finanzjarju',
  'financing-and-investment-dynamics' => 'Għal żona waħda',
  'financing-and-investment-dynamics2' => 'Qabbel żewġ żoni',
  'financing-and-investment-dynamics_main' => 'Żviluppi fil-finanzjament u l-investiment',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Ir-rati ta’ tkabbir fis-self għad-djar qed jiżdiedu b’mod kostanti fiż-żona tal-euro',
  'inflation-rates' => 'Indiċi ta\' prezzijiet għall-konsumatur',
  'international-investment-position' => 'Pożizzjoni tal-investiment internazzjonali',
  'investment-funds-assets' => 'Assi',
  'investment-funds-in-the-euro-area' => 'Fondi tal-investiment taż-żona tal-euro',
  'investment-funds-liabilities' => 'Obbligazzjonijiet',
  'investment-funds-policies' => 'Skont il-polza tal-investiment',
  'investment-funds-types' => 'Skont it-tip ta\' fond',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Ħruġ ta’ titoli tad-dejn minn residenti taż-żona tal-euro',
  'macro-economic-indicators' => 'Indikaturi makroekonomiċi',
  'macroeconomic-scoreboard' => 'Skorbord Makroekonomiku',
  'payment-statistics' => 'Ħlasijiet bil-kard fiż-żona tal-euro jirdoppjaw f’għaxar snin.',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Tkompli x-xejra pożittiva tas-self bankarju lill-korporattivi fiż-żona tal-euro',
  'reserve-assets' => 'Attiv ta’ riżerva',
  'securities-debt-securities' => 'Titoli ta\' dejn',
  'securities-quoted-shares' => 'Ishma elenkati',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Ir-rata tal-euro fuq terminu qasir (€STR) hija r-rata tal-imgħax tas-suq tal-flus tal-euro overnight',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'L-€STR mxiet fil-medda -0.583 u -0.511 mit-tnedija tagħha fit-2 ta’ Ottubru 2019.',
));
