<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Talletukset',
  'bank-interest-rates-loans' => 'Lainat',
  'banks-balance-sheet-deposits' => 'Talletukset',
  'banks-balance-sheet-loans' => 'Lainat',
  'competitiveness-indicators' => 'Hinnat ja kustannukset',
  'corporates-debt-ratio-in-the-euro-area' => 'Yritysten velkasuhde vaihtelee euroalueella',
  'crypto-assets' => 'Kryptovarat: kehitys ja näkökulmat',
  'current-account-balance-of-the-euro-area' => 'Euroalueen vaihtotase',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Noteerattujen osakkeiden markkina-arvon kehitys vaihtelee euroalueen eri maissa',
  'current-account-by-main-counterparties' => 'Vaihtotase (keskeiset vastapuolet)',
  'digpub-1' => '<p>Digitaaliseen julkaisuun</p>
<p>Raha, luotonanto ja ohjauskorot</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Euroalueen pankkilainojen korot',
  'external-debt' => 'Ulkomainen velka',
  'external-sector' => 'Vaihtotase',
  'financial-account' => 'Rahoitustase',
  'financing-and-investment-dynamics' => 'Aluekohtaiset tiedot',
  'financing-and-investment-dynamics2' => 'Aluekohtaisten tietojen vertailu',
  'financing-and-investment-dynamics_main' => 'Rahoitus ja sijoitukset',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Asuntolainakanta kasvaa tasaisesti euroalueella',
  'inflation-rates' => 'Kuluttajahintaindeksi',
  'international-investment-position' => 'Ulkomainen varallisuusasema',
  'investment-funds-assets' => 'Saamiset',
  'investment-funds-in-the-euro-area' => 'Euroalueen sijoitusrahastot',
  'investment-funds-liabilities' => 'Velat',
  'investment-funds-policies' => 'Rahaston sijoituskohde',
  'investment-funds-types' => 'Rahastotyyppi',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Velkapaperien liikkeeseenlasku euroalueella',
  'macro-economic-indicators' => 'Makrotalouden indikaattorit',
  'macroeconomic-scoreboard' => 'Makrotalouden epätasapainon seuranta',
  'payment-statistics' => 'Korttimaksujen määrä euroalueella kaksinkertaistui kymmenessä vuodessa',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Pankkien lainananto yrityksille kehittyy myönteisesti euroalueella',
  'reserve-assets' => 'Valuuttavaranto',
  'securities-debt-securities' => 'Velkapaperit',
  'securities-quoted-shares' => 'Noteeratut osakkeet',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => '€STR on euromääräisten yön yli -rahamarkkinoiden korko‏',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => '€STR-korko on 2.10.2019 jälkeen vaihdellut välillä -0,583 ja -0,511, ja 29.3.2021 se oli -0,570.',
));
