<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Deposits',
  'bank-interest-rates-loans' => 'Loans',
  'banks-balance-sheet-deposits' => 'Deposits',
  'banks-balance-sheet-loans' => 'Loans',
  'competitiveness-indicators' => 'By price and cost',
  'corporates-debt-ratio-in-the-euro-area' => 'Corporate debt ratio varies across the euro area',
  'crypto-assets' => 'Crypto assets: developments and perspectives',
  'current-account-balance-of-the-euro-area' => 'Current account balance of the euro area',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Developments in the market value of listed shares vary across the euro area',
  'current-account-by-main-counterparties' => 'Current account by main counterparties',
  'digpub-1' => '<p>Go to digital publication</p>
<p>Money, credit and central bank interest rates</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Euro area interest rates on bank loans',
  'external-debt' => 'External debt',
  'external-sector' => 'Current account',
  'financial-account' => 'Financial account',
  'financing-and-investment-dynamics' => 'For one area',
  'financing-and-investment-dynamics2' => 'Compare two areas',
  'financing-and-investment-dynamics_main' => 'Financing and investment dynamics',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Growth rates in housing loans are steadily increasing in the euro area',
  'inflation-rates' => 'Index of consumer prices',
  'international-investment-position' => 'International investment position',
  'investment-funds-assets' => 'Assets',
  'investment-funds-in-the-euro-area' => 'Investment funds in the euro area',
  'investment-funds-liabilities' => 'Liabilities',
  'investment-funds-policies' => 'By investment policy',
  'investment-funds-types' => 'By type of fund',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Issuance of debt securities by euro area residents',
  'macro-economic-indicators' => 'Macroeconomic indicators',
  'macroeconomic-scoreboard' => 'Macroeconomic Scoreboard',
  'payment-statistics' => 'Euro area card payments double in a decade',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Positive trend in euro area bank loans to corporates continues',
  'reserve-assets' => 'Reserve assets',
  'securities-debt-securities' => 'Debt Securities',
  'securities-quoted-shares' => 'Listed shares',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'The euro short-term rate (€STR) is the euro overnight money market interest rate',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'The €STR has moved within the range -0.583 and -0.511 since its launch on 2 October 2019.',
));
