<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Depozite',
  'bank-interest-rates-loans' => 'Credite',
  'banks-balance-sheet-deposits' => 'Depozite',
  'banks-balance-sheet-loans' => 'Credite',
  'competitiveness-indicators' => 'În funcție de prețuri și de costuri',
  'corporates-debt-ratio-in-the-euro-area' => 'Ponderea datoriei societăților în PIB variază la nivelul zonei euro',
  'crypto-assets' => 'Criptoactivele: evoluții și perspective',
  'current-account-balance-of-the-euro-area' => 'Soldul contului curent al zonei euro',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Evoluțiile valorii de piață a acțiunilor cotate variază la nivelul zonei euro',
  'current-account-by-main-counterparties' => 'Contul curent în funcție de contrapartidele principale',
  'digpub-1' => '<p>Accesează publicația digitală</p>
<p>Moneda, creditul și ratele dobânzilor băncilor centrale</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Ratele dobânzilor la împrumuturile bancare în zona euro',
  'external-debt' => 'Datoria externă',
  'external-sector' => 'Cont curent',
  'financial-account' => 'Contul financiar',
  'financing-and-investment-dynamics' => 'Pentru o zonă',
  'financing-and-investment-dynamics2' => 'Comparați două zone',
  'financing-and-investment-dynamics_main' => 'Dinamica finanțării și a investițiilor',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Ritmurile de creștere ale creditelor imobiliare înregistrează o creștere constantă în zona euro',
  'inflation-rates' => 'Indicele prețurilor de consum',
  'international-investment-position' => 'Poziția investițională internațională',
  'investment-funds-assets' => 'Active',
  'investment-funds-in-the-euro-area' => 'Fondurile de investiții din zona euro',
  'investment-funds-liabilities' => 'Pasive',
  'investment-funds-policies' => 'Pe politici de investiții',
  'investment-funds-types' => 'Pe categorii de fonduri',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Emisiunea de titluri de natura datoriei de către rezidenții zonei euro',
  'macro-economic-indicators' => 'Indicatori macroeconomici',
  'macroeconomic-scoreboard' => 'Tablou de bord macroeconomic',
  'payment-statistics' => 'Plățile prin card în zona euro s-au dublat într-un deceniu',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Trendul pozitiv al împrumuturilor bancare acordate societăților în zona euro continuă',
  'reserve-assets' => 'Active de rezervă',
  'securities-debt-securities' => 'Titluri de natura datoriei',
  'securities-quoted-shares' => 'Acțiuni cotate',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Rata dobânzii pe termen scurt la operațiunile în euro (€STR) este rata dobânzii <em>overnight</em> pe piața monetară din zona euro',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'De la lansarea sa la data de 2 octombrie 2019, €STR a fluctuat în intervalul cuprins între -0,583 și -0,511.',
));
