<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Inlåning',
  'bank-interest-rates-loans' => 'Lån',
  'banks-balance-sheet-deposits' => 'Inlåning',
  'banks-balance-sheet-loans' => 'Lån',
  'competitiveness-indicators' => 'Per pris och kostnad',
  'corporates-debt-ratio-in-the-euro-area' => 'Företagens skuldsättningsgrad i euroområdet',
  'crypto-assets' => 'Kryptotillgångar: utveckling och perspektiv',
  'current-account-balance-of-the-euro-area' => 'Euroområdets bytesbalans',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Utvecklingen av marknadsvärdet för noterade aktier varierar inom euroområdet',
  'current-account-by-main-counterparties' => 'Bytesbalans (större motparter)',
  'digpub-1' => '<p>Gå till digital publikation</p>
<p>Pengar, lån och centralbanksräntor</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Räntor på banklån i euroområdet',
  'external-debt' => 'Utlandsskuld',
  'external-sector' => 'Bytesbalans',
  'financial-account' => 'Finansiell balans',
  'financing-and-investment-dynamics' => 'För ett område',
  'financing-and-investment-dynamics2' => 'Jämför två områden',
  'financing-and-investment-dynamics_main' => 'Finansierings- och investeringsdynamik',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Bolån ökar stadigt i euroområdet',
  'inflation-rates' => 'Konsumentprisindex',
  'international-investment-position' => 'Utlandsställning (i.i.p.)',
  'investment-funds-assets' => 'Tillgångar',
  'investment-funds-in-the-euro-area' => 'Investeringsfonder i euroområdet',
  'investment-funds-liabilities' => 'Skulder',
  'investment-funds-policies' => 'Per investeringsslag',
  'investment-funds-types' => 'Per typ av fond',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Emission av skuldförbindelser av hemmahörande i euroområdet',
  'macro-economic-indicators' => 'Makroekonomiska indikatorer',
  'macroeconomic-scoreboard' => 'Makroekonomisk resultattavla',
  'payment-statistics' => 'Kortbetalningar i euroområdet har fördubblats under ett decennium',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Den positiva trenden i banklån till företag i euroområdet fortsätter',
  'reserve-assets' => 'Valutareserven',
  'securities-debt-securities' => 'Skuldförbindelser',
  'securities-quoted-shares' => 'Noterade aktier',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Den korta euroräntan (€STR) är den nya dagslåneräntan i euro',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => '€STR har varit stabil, främst i intervallet mellan [-0,550] och [-0,511] sedan introduktionen den 2 oktober 2019, och låg på [-0,549] den [X] september 2020.',
));
