<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Betét',
  'bank-interest-rates-loans' => 'Hitel',
  'banks-balance-sheet-deposits' => 'Betét',
  'banks-balance-sheet-loans' => 'Hitel',
  'competitiveness-indicators' => 'Ár és költség szerint',
  'corporates-debt-ratio-in-the-euro-area' => 'A vállalati adósságmutató euroövezet-szerte változó képet mutat',
  'crypto-assets' => 'Kriptoeszközök: folyamatok és nézőpontok',
  'current-account-balance-of-the-euro-area' => 'Az euroövezetet folyó fizetési mérlegének egyenlege',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'A tőzsdei részvények piaci értéke az euroövezet különböző pontjain eltérően alakul',
  'current-account-by-main-counterparties' => 'Folyó fizetési mérleg fő partnerek szerint',
  'digpub-1' => '<p>Ugrás a digitális kiadványhoz</p>
<p>Pénz, hitel és központi banki kamatlábak</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Euroövezeti banki hitelkamatlábak',
  'external-debt' => 'Külföldi adósság',
  'external-sector' => 'Folyó fizetési mérleg',
  'financial-account' => 'A pénzügyi mérleg',
  'financing-and-investment-dynamics' => 'Egy területhez',
  'financing-and-investment-dynamics2' => 'Két terület összevetése',
  'financing-and-investment-dynamics_main' => 'Finanszírozási és befektetési dinamika',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'A lakáshitelek növekedési üteme kitartóan emelkedik az euroövezetben',
  'inflation-rates' => 'Fogyasztóiár-index',
  'international-investment-position' => 'Nemzetközi befektetési pozíció',
  'investment-funds-assets' => 'Eszköz',
  'investment-funds-in-the-euro-area' => 'Befektetési alapok az euroövezetben',
  'investment-funds-liabilities' => 'Forrás',
  'investment-funds-policies' => 'Befektetési politika szerint',
  'investment-funds-types' => 'Alaptípus szerint',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Euroövezetbeli rezidensek adósságpapír-kibocsátása',
  'macro-economic-indicators' => 'Makrogazdasági mutatók',
  'macroeconomic-scoreboard' => 'Makrogazdasági eredménytábla',
  'payment-statistics' => 'Egy évtized alatt megduplázódott az euroövezeti kártyás fizetésforgalom',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Folytatódik a vállalatoknak nyújtott euroövezeti bankhitelek pozitív trendje',
  'reserve-assets' => 'Tartalékeszközök',
  'securities-debt-securities' => 'Hitelpapír',
  'securities-quoted-shares' => 'Tőzsdei részvény',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'A rövid lejáratú eurokamatláb (€STR) az euro egynapos pénzpiaci kamatlába',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Az €STR a 2019. október 2-i bevezetése óta a −0,583 és a −0,511 tartományon belül ingadozott. 2021. március 29-én −0,570 volt.',
));
