<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Vloge',
  'bank-interest-rates-loans' => 'Posojila',
  'banks-balance-sheet-deposits' => 'Vloge',
  'banks-balance-sheet-loans' => 'Posojila',
  'competitiveness-indicators' => 'Po cenah in stroških',
  'corporates-debt-ratio-in-the-euro-area' => 'Stopnja zadolženosti podjetij je v euroobmočju različna',
  'crypto-assets' => 'Kriptoimetja: dosedanja gibanja in obeti',
  'current-account-balance-of-the-euro-area' => 'Saldo tekočega računa v euroobmočju',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Gibanje tržne vrednosti delnic, ki kotirajo na borzi, se med državami euroobmočja razlikuje',
  'current-account-by-main-counterparties' => 'Tekoči račun po glavnih nasprotnih strankah',
  'digpub-1' => '<p>Odpri digitalno publikacijo</p>
<p>Denar, krediti in centralnobančne obrestne mere</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Obrestne mere za bančna posojila v euroobmočju',
  'external-debt' => 'Zunanji dolg',
  'external-sector' => 'Tekoči račun',
  'financial-account' => 'Finančni račun',
  'financing-and-investment-dynamics' => 'Ena država/območje',
  'financing-and-investment-dynamics2' => 'Primerjava dveh držav/območij',
  'financing-and-investment-dynamics_main' => 'Financiranje in naložbe',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Stopnja rasti stanovanjskih posojil se v euroobmočju vztrajno povečuje',
  'inflation-rates' => 'Indeks cen življenjskih potrebščin',
  'international-investment-position' => 'Stanje mednarodnih naložb',
  'investment-funds-assets' => 'Sredstva',
  'investment-funds-in-the-euro-area' => 'Investicijski skladi v euroobmočju',
  'investment-funds-liabilities' => 'Obveznosti',
  'investment-funds-policies' => 'Po naložbeni politiki',
  'investment-funds-types' => 'Po vrsti sklada',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Izdajanje dolžniških vrednostnih papirjev s strani rezidentov euroobmočja',
  'macro-economic-indicators' => 'Makroekonomski kazalniki',
  'macroeconomic-scoreboard' => 'Makroekonomska preglednica',
  'payment-statistics' => 'Kartična plačila so se v euroobmočju v enem desetletju podvojila',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Pozitivni trend pri bančnih posojilih gospodarskim družbam v euroobmočju se nadaljuje',
  'reserve-assets' => 'Rezervna imetja',
  'securities-debt-securities' => 'Dolžniški vrednostni papirji',
  'securities-quoted-shares' => 'Delnice, ki kotirajo na borzi',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Eurska kratkoročna obrestna mera (€STR) je obrestna mera eurskega denarnega trga čez noč',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Od uvedbe 2. oktobra 2019 se €STR giblje v razponu od −0,583 do −0,511.',
));
