<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Einlagen',
  'bank-interest-rates-loans' => 'Kredite',
  'banks-balance-sheet-deposits' => 'Einlagen',
  'banks-balance-sheet-loans' => 'Kredite',
  'competitiveness-indicators' => 'Nach Preisen und Kosten',
  'corporates-debt-ratio-in-the-euro-area' => 'Schuldenquote der Unternehmen fällt im Euro-Währungsgebiet unterschiedlich aus',
  'crypto-assets' => 'Crypto-Assets: Entwicklungen und Perspektiven',
  'current-account-balance-of-the-euro-area' => 'Leistungsbilanz des Euro-Währungsgebiets',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Marktwert börsennotierter Aktien entwickelt sich in den Euro-Ländern unterschiedlich',
  'current-account-by-main-counterparties' => 'Leistungsbilanz (nach Hauptgeschäftspartnern)',
  'digpub-1' => '<p>Weiter zur digitalen Publikation</p>
<p>Geld, Kredite und Notenbankzinsen</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Zinssätze für Bankkredite im Euro-Währungsgebiet',
  'external-debt' => 'Auslandsverschuldung',
  'external-sector' => 'Leistungsbilanz',
  'financial-account' => 'Kapitalbilanz',
  'financing-and-investment-dynamics' => 'Für ein Gebiet',
  'financing-and-investment-dynamics2' => 'Vergleich von zwei Gebieten',
  'financing-and-investment-dynamics_main' => 'Finanzierungs- und Investitionsdynamik',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Wachstumsraten der Wohnungsbaukredite steigen im Euroraum stetig an',
  'inflation-rates' => 'Verbraucherpreisindex',
  'international-investment-position' => 'Auslandsvermögensstatus',
  'investment-funds-assets' => 'Aktiva',
  'investment-funds-in-the-euro-area' => 'Investmentfonds im Euro-Währungsgebiet',
  'investment-funds-liabilities' => 'Passiva',
  'investment-funds-policies' => 'Nach Anlageschwerpunkten',
  'investment-funds-types' => 'Nach Art des Fonds',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Emission von Schuldverschreibungen durch Ansässige im Euro-Währungsgebiet',
  'macro-economic-indicators' => 'Makroökonomische Indikatoren',
  'macroeconomic-scoreboard' => 'Makroökonomisches Scoreboard',
  'payment-statistics' => 'Kartenzahlungen im Euroraum verdoppeln sich innerhalb von zehn Jahren',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Positiver Trend im Euroraum bei Bankkrediten an Kapitalgesellschaften hält an',
  'reserve-assets' => 'Währungsreserven',
  'securities-debt-securities' => 'Schuldverschreibungen',
  'securities-quoted-shares' => 'Börsennotierte Aktien',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Der €STR ist der Übernacht-Zinssatz für den Euro-Geldmarkt',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Der €STR bewegt sich seit seiner Veröffentlichung am 2. Oktober 2019 in einer Spanne zwischen -0,583 und -0,511.',
));
