<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'depoziti',
  'bank-interest-rates-loans' => 'krediti',
  'banks-balance-sheet-deposits' => 'depoziti',
  'banks-balance-sheet-loans' => 'krediti',
  'competitiveness-indicators' => 'po cijenama i troškovima',
  'corporates-debt-ratio-in-the-euro-area' => 'Stopa duga poduzeća razlikuje se među državama europodručja',
  'crypto-assets' => 'Kriptoimovina: kretanja i izgledi',
  'current-account-balance-of-the-euro-area' => 'Saldo tekućeg računa europodručja',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Kretanje tržišne vrijednosti dionica koje kotiraju na burzi razlikuje se među državama europodručja.',
  'current-account-by-main-counterparties' => 'Tekući račun po glavnim protustrankama',
  'digpub-1' => '<p>Digitalna publikacija</p>
<p>Novac, krediti i kamatne stope središnje banke</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Kamatne stope na bankovne kredite u europodručju',
  'external-debt' => 'inozemni dug',
  'external-sector' => 'tekući račun platne bilance',
  'financial-account' => 'financijski račun',
  'financing-and-investment-dynamics' => 'Jedno područje',
  'financing-and-investment-dynamics2' => 'Usporedi dva područja',
  'financing-and-investment-dynamics_main' => 'Dinamika financiranja i ulaganja',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Stope rasta stambenih kredita u europodručju kontinuirano rastu',
  'inflation-rates' => 'indeks potrošačkih cijena',
  'international-investment-position' => 'stanje međunarodnih ulaganja',
  'investment-funds-assets' => 'imovina',
  'investment-funds-in-the-euro-area' => 'Investicijski fondovi u europodručju',
  'investment-funds-liabilities' => 'obveze',
  'investment-funds-policies' => 'prema investicijskoj politici',
  'investment-funds-types' => 'prema vrsti fonda',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Izdavanje dužničkih vrijednosnih papira od rezidenata europodručja',
  'macro-economic-indicators' => 'Makroekonomski pokazatelji',
  'macroeconomic-scoreboard' => 'Makroekonomska tablica rezultata',
  'payment-statistics' => 'Kartična plaćanja u europodručju udvostručila su se u proteklom desetljeću',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Nastavlja se pozitivan trend bankovnih kredita poduzećima u europodručju',
  'reserve-assets' => 'devizne pričuve',
  'securities-debt-securities' => 'dužnički vrijednosni papiri',
  'securities-quoted-shares' => 'dionice koje kotiraju na burzi',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Eurska kratkoročna kamatna stopa (€STR) eurska je prekonoćna kamatna stopa na tržištu novca',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Otkako je uveden 2. listopada 2019., €STR se kreće između –0,583 i –0,511 a 29. ožujka 2021. iznosio je –0,570.',
));
