<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Vklady',
  'bank-interest-rates-loans' => 'Úvěry',
  'banks-balance-sheet-deposits' => 'Vklady',
  'banks-balance-sheet-loans' => 'Úvěry',
  'competitiveness-indicators' => 'Podle cen a nákladů',
  'corporates-debt-ratio-in-the-euro-area' => 'Rozdíly v ukazateli zadluženosti podniků v rámci eurozóny',
  'crypto-assets' => 'Kryptoaktiva: vývoj a perspektivy',
  'current-account-balance-of-the-euro-area' => 'Saldo běžného účtu eurozóny',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Vývoj tržní hodnoty kotovaných akcií se v jednotlivých zemích eurozóny liší.',
  'current-account-by-main-counterparties' => 'Běžný účet podle hlavních protistran',
  'digpub-1' => '<p>Jít na digitální publikaci</p>
<p>Peníze, úvěry a úrokové sazby centrálních bank</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Úrokové sazby z bankovních úvěrů v eurozóně',
  'external-debt' => 'Zahr. zadluženost',
  'external-sector' => 'Běžný účet',
  'financial-account' => 'Finanční účet',
  'financing-and-investment-dynamics' => 'Pro jednu oblast',
  'financing-and-investment-dynamics2' => 'Porovnejte dvě oblasti',
  'financing-and-investment-dynamics_main' => 'Dynamika financování a investic',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Tempa růstu úvěrů na bydlení v eurozóně setrvale rostou',
  'inflation-rates' => 'index spotřebitelských cen',
  'international-investment-position' => 'Investiční pozice vůči zahraničí',
  'investment-funds-assets' => 'Aktiva',
  'investment-funds-in-the-euro-area' => 'Investiční fondy v eurozóně',
  'investment-funds-liabilities' => 'Pasiva',
  'investment-funds-policies' => 'Podle investiční politiky',
  'investment-funds-types' => 'Podle druhu fondu',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Vydávání dluhových cenných papírů rezidenty eurozóny',
  'macro-economic-indicators' => 'Makroekonomické ukazatele',
  'macroeconomic-scoreboard' => 'Makroekon. srovnávací přehled',
  'payment-statistics' => 'Platby kartou v eurozóně se během desetiletí zdvojnásobily',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Pozitivní trend poskytování bankovních úvěrů podnikům v eurozóně pokračuje',
  'reserve-assets' => 'Rezervní aktiva',
  'securities-debt-securities' => 'Dluhové cenné papíry',
  'securities-quoted-shares' => 'Kotované akcie',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Krátkodobá eurová sazba (€STR) je jednodenní úroková sazba na peněžním trhu s eurem',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Sazba €STR se od svého zahájení 2. října 2019 pohybuje v rozpětí -0,583 a -0,511. 29. března 2021 byla na úrovni -0,570.',
));
