<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Depozyty',
  'bank-interest-rates-loans' => 'Kredyty',
  'banks-balance-sheet-deposits' => 'Depozyty',
  'banks-balance-sheet-loans' => 'Kredyty',
  'competitiveness-indicators' => 'Według cen i kosztów',
  'corporates-debt-ratio-in-the-euro-area' => 'Zróżnicowanie wskaźnika zadłużenia przedsiębiorstw w strefie euro',
  'crypto-assets' => 'Kryptoaktywa: rozwój i perspektywy',
  'current-account-balance-of-the-euro-area' => 'Saldo rachunku bieżącego strefy euro',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Wartość rynkowa akcji giełdowych kształtuje się różnie w poszczególnych krajach strefy euro',
  'current-account-by-main-counterparties' => 'Rachunek bieżący według głównych kontrahentów',
  'digpub-1' => '<p>Przejdź do publikacji cyfrowej</p>
<p>Pieniądz, kredyty i stopy procentowe banku centralnego</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Oprocentowanie kredytów bankowych w strefie euro',
  'external-debt' => 'Dług zewnętrzny',
  'external-sector' => 'Rachunek bieżący',
  'financial-account' => 'Rachunek finansowy',
  'financing-and-investment-dynamics' => 'Dla jednego obszaru',
  'financing-and-investment-dynamics2' => 'Porównanie dwóch obszarów',
  'financing-and-investment-dynamics_main' => 'Dynamika finansowania i inwestycji',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Dynamika kredytów mieszkaniowych w strefie euro równomiernie wzrasta',
  'inflation-rates' => 'Wskaźnik cen konsumpcyjnych',
  'international-investment-position' => 'Międzynarodowa pozycja inwestycyjna',
  'investment-funds-assets' => 'Aktywa',
  'investment-funds-in-the-euro-area' => 'Fundusze inwestycyjne w strefie euro',
  'investment-funds-liabilities' => 'Zobowiązania',
  'investment-funds-policies' => 'Według polityki inwestycyjnej',
  'investment-funds-types' => 'Według typu funduszu',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Emisja papierów dłużnych przez rezydentów strefy euro',
  'macro-economic-indicators' => 'Wskaźniki makroekonomiczne',
  'macroeconomic-scoreboard' => 'Tablica wskaźników makroekonomicznych',
  'payment-statistics' => 'Liczba płatności kartowych w strefie euro w ciągu dekady się podwoiła',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'W strefie euro utrzymuje się pozytywny trend w kredytach dla przedsiębiorstw',
  'reserve-assets' => 'Aktywa rezerwowe',
  'securities-debt-securities' => 'Dłużne papiery wartościowe',
  'securities-quoted-shares' => 'Akcje notowane',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Stawka €STR to stopa referencyjna oparta na transakcjach rynku pieniężnego euro z terminem overnight',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'Krótkoterminowa stopa dla euro €STR została pierwszy raz ogłoszona 2 października 2019 i od tego czasu oscyluje w przedziale od −0,583 do −0,511.',
));
