<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Depósitos',
  'bank-interest-rates-loans' => 'Préstamos y créditos',
  'banks-balance-sheet-deposits' => 'Depósitos',
  'banks-balance-sheet-loans' => 'Préstamos y créditos',
  'competitiveness-indicators' => 'En términos de precios y costes',
  'corporates-debt-ratio-in-the-euro-area' => 'La ratio de endeudamiento de las empresas varía entre los países de la zona del euro',
  'crypto-assets' => 'Criptoactivos: novedades y perspectivas',
  'current-account-balance-of-the-euro-area' => 'Balanza por cuenta corriente de la zona del euro',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'La evolución del valor de mercado de las acciones cotizadas difiere entre países de la zona del euro',
  'current-account-by-main-counterparties' => 'Cuenta corriente por contrapartidas principales',
  'digpub-1' => '<p>Ir a publicación digital</p>
<p>Dinero, crédito y tipos de interés de los bancos centrales</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Tipos de interés aplicados por las entidades de crédito de la zona del euro',
  'external-debt' => 'Deuda exterior',
  'external-sector' => 'Cuenta corriente',
  'financial-account' => 'Cuenta financiera',
  'financing-and-investment-dynamics' => 'Para un país',
  'financing-and-investment-dynamics2' => 'Comparar dos países',
  'financing-and-investment-dynamics_main' => 'Dinámica de financiación e inversión',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Las tasas de crecimiento de los préstamos para adquisición de vivienda aumentan de forma sostenida en la zona del euro',
  'inflation-rates' => 'Índice de precios de consumo',
  'international-investment-position' => 'Posición de inversión internacional',
  'investment-funds-assets' => 'Activos',
  'investment-funds-in-the-euro-area' => 'Fondos de inversión en la zona del euro',
  'investment-funds-liabilities' => 'Pasivos',
  'investment-funds-policies' => 'Por política de inversión',
  'investment-funds-types' => 'Por tipo de fondo',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Emisión de valores representativos de deuda por residentes en la zona del euro',
  'macro-economic-indicators' => 'Indicadores macroeconómicos',
  'macroeconomic-scoreboard' => 'Cuadro de indicadores macroeconómicos',
  'payment-statistics' => 'Los pagos con tarjeta en la zona del euro se han duplicado en la última década',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'Continúa la tendencia positiva de los préstamos bancarios a las empresas en la zona del euro',
  'reserve-assets' => 'Activos de reserva',
  'securities-debt-securities' => 'Valores representativos de deuda',
  'securities-quoted-shares' => 'Acciones cotizadas',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'El tipo de interés a corto plazo del euro (€STR) es el tipo de interés a un día del mercado monetario del euro',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => 'El €STR oscila en un intervalo comprendido entre -0,583 y -0,511 desde que comenzó a publicarse el 2 de octubre de 2019.',
));
