<?php

$langIndexDefault=array(
'projects' => array (
  'bank-interest-rates-deposits' => 'Indlån',
  'bank-interest-rates-loans' => 'Udlån',
  'banks-balance-sheet-deposits' => 'Indlån',
  'banks-balance-sheet-loans' => 'Lån',
  'competitiveness-indicators' => 'Priser og omkostninger',
  'corporates-debt-ratio-in-the-euro-area' => 'Virksomhedernes gæld varierer i euroområdet',
  'crypto-assets' => 'Kryptoaktiver: udvikling og perspektiver',
  'current-account-balance-of-the-euro-area' => 'De løbende poster på euroområdets betalingsbalance',
  'developments-in-the-market-value-of-listed-shares-vary-across-the-euro-area' => 'Udviklingen i markedsværdien på noterede aktier er forskellig i de forskellige lande i euroområdet',
  'current-account-by-main-counterparties' => 'Løbende poster pr. vigtigste modpart',
  'digpub-1' => '<p>Til digital publikation</p>
<p>Pengepolitiske, udlåns- og centralbankrenter</p>',
  'euro-area-and-national-breakdowns-of-banks-loans-and-deposit-interest-rates' => 'Renter på banklån i euroområdet',
  'external-debt' => 'Udlandsgæld',
  'external-sector' => 'Løbende poster',
  'financial-account' => 'Finansiel konto',
  'financing-and-investment-dynamics' => 'For et område',
  'financing-and-investment-dynamics2' => 'Sammenlign to områder',
  'financing-and-investment-dynamics_main' => 'Finansierings- og investeringsaktivitet',
  'growth-rates-in-housing-loans-are-steadily-increasing-in-the-euro-area' => 'Væksten i boliglån stiger støt i euroområdet',
  'inflation-rates' => 'Forbrugerprisindeks',
  'international-investment-position' => 'Udenlandske direkte investeringer',
  'investment-funds-assets' => 'Aktiver',
  'investment-funds-in-the-euro-area' => 'Investeringsforeninger i euroområdet',
  'investment-funds-liabilities' => 'Passiver',
  'investment-funds-policies' => 'Investeringspolitik',
  'investment-funds-types' => 'Type investeringsforening',
  'issuance-of-debt-securities-by-euro-area-residents' => 'Residenter i euroområdets udstedelse af gældsinstrumenter',
  'macro-economic-indicators' => 'Makroøkonomiske indikatorer',
  'macroeconomic-scoreboard' => 'Makroøkonomisk resultattavle',
  'payment-statistics' => 'Kortbetalingerne i euroområdet er fordoblet i løbet af ti år',
  'positive-trend-in-euro-area-bank-loans-to-corporates-continues' => 'En fortsat positiv udvikling i banklån til virksomheder i euroområdet',
  'reserve-assets' => 'Reserveaktiver',
  'securities-debt-securities' => 'Gældsinstrumenter',
  'securities-quoted-shares' => 'Noterede aktier',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate' => 'Den korte eurorente (€STR) er dag til dag-europengemarkedsrenten',
    'the-euro-short-term-rate-str-is-the-euro-overnight-money-market-interest-rate_highlight' => '€STR har bevæget sig inden for intervallet -0,583 og -0,511 siden lanceringen 2. oktober 2019.',
));
